### ISSUE TITLE
Linux: Cache the boost build from within manylinux to the host and back

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/electrumsv-node#15]
The boost build takes around 40 minutes at this time. It should be possible to just send to/retrieve from the host `/opt/boost_1_70` and let Azure take care of caching it. This would speed up the node building process by 20 minutes.

**Comment by rt121212121** [comment]
If #16 is done, then this becomes less of a win. In fact, this may be quite fragile and problematic, so it should be considered strongly before committing any working implementation whether the cost is bigger than the gains.

**Comment by AustEcon** [comment]
I think this issue can be closed now... 

The workaround was to make a custom Centos7 docker image with required system dependencies for compiling the node (including Boost 1.70)

Then in Azure, we can run the node compilation in the container and share it via the mounted volume: $(Build.BinariesDirectory) (mounted by default in Azure).

Then the next step of the job is the manylinux wheel build which can proceed as a fairly straightforward thing.
