### ISSUE TITLE
Only 64 bit python3.6, 3.7 and 3.8 supported on windows at present

### ISSUE THREAD

**Issue by AustEcon** [electrumsv/electrumsv-node#2]

**Comment by AustEcon** [comment]
I need to make a 32 bit wheel for windows and for linux need to make a "manylinux" wheel... which I don't feel like doing right now...

**Comment by rt121212121** [comment]
This is for testing and development, not end user support. People can be expected to be 64 bits python 3.7 or 8.

**Comment by AustEcon** [comment]
Sure. I'd like to have linux working for my own benefit though at some point.

**Comment by AustEcon** [comment]
32 and 64 bit supported now
