### ISSUE TITLE
Module: Should support starting on Linux

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/electrumsv-node#8]
QED

**Comment by rt121212121** [comment]
Implemented but untested.

1. Install the package either locally or via PyPI.
2. Enter `python3.7` interpreter.
3. Execute `from electrumsv_node import electrumsv_node`.
4. Execute `electrumsv_node.start()`.
5. Observe a returned process id.
6. Exit the interpreter (Control+D).
7. Look at running processes for `bitcoind` and the given process ID.

**Comment by AustEcon** [comment]
I've added unititests to azure pipelines (after manually installing from the generated wheels).

Maybe this ^^ is covered by that then?
